# Generated by Copilot on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['name'], name='feedback_t_name_3dd3b8_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['date'], name='feedback_f_date_1a2f45_idx'),
        ),
    ]