# Generated by Copilot on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_date_index_topic_name_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feedback',
            name='feedback_f_date_1a2f45_idx',
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['rating'], name='feedback_r_rating_1f8b65_idx'),
        ),
    ]